clear all;
close all;
fc = 100;
fm = 10;
t = 0:0.00001:0.5; 
B = 10;
c = cos (2*pi*fc*t);
m = cos (2*pi*fm*t);
y = cos (2*pi*fc*t+ (B*sin(2*pi*fm*t))); 
subplot (311), plot (t,m, 'r', 'Linewidth', 2);
xlabel('Time');
ylabel('Amplitude');
title('Message Signal');
subplot (312), plot (t,c, 'Linewidth',2);
xlabel('Time');
ylabel('Amplitude');
title('Carrier Signal');
subplot (313), plot (t, y, 'k', 'Linewidth',2);
xlabel('Time');
ylabel('Amplitude');
title('FM Signal');